import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Navbar from "@/components/_custom-components/navbar";
import Footer from "@/components/_custom-components/footer";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "flex min-h-screen flex-col items-center justify-between bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Navbar />
        {children}
         <Footer /> 
      </body>
    </html>
  );
}
